export const COLOMBIA_DEPARTMENTS = [
  { id: "CO-AMA", name: "Amazonas" },
  { id: "CO-ANT", name: "Antioquia" },
  { id: "CO-ARA", name: "Arauca" },
  { id: "CO-ATL", name: "Atlántico" },
  { id: "CO-BOL", name: "Bolívar" },
  { id: "CO-BOY", name: "Boyacá" },
  { id: "CO-CAL", name: "Caldas" },
  { id: "CO-CAQ", name: "Caquetá" },
  { id: "CO-CAS", name: "Casanare" },
  { id: "CO-CAU", name: "Cauca" },
  { id: "CO-CES", name: "Cesar" },
  { id: "CO-CHO", name: "Chocó" },
  { id: "CO-COR", name: "Córdoba" },
  { id: "CO-CUN", name: "Cundinamarca" },
  { id: "CO-DC", name: "Bogotá, D.C." },
  { id: "CO-GUA", name: "Guainía" },
  { id: "CO-GUV", name: "Guaviare" },
  { id: "CO-HUI", name: "Huila" },
  { id: "CO-LAG", name: "La Guajira" },
  { id: "CO-MAG", name: "Magdalena" },
  { id: "CO-MET", name: "Meta" },
  { id: "CO-NAR", name: "Nariño" },
  { id: "CO-NSA", name: "Norte de Santander" },
  { id: "CO-PUT", name: "Putumayo" },
  { id: "CO-QUI", name: "Quindío" },
  { id: "CO-RIS", name: "Risaralda" },
  { id: "CO-SAN", name: "Santander" },
  { id: "CO-SAP", name: "San Andrés y Providencia" },
  { id: "CO-SUC", name: "Sucre" },
  { id: "CO-TOL", name: "Tolima" },
  { id: "CO-VAC", name: "Valle del Cauca" },
  { id: "CO-VAU", name: "Vaupés" },
  { id: "CO-VID", name: "Vichada" }
];
